logging:
  level:
    ROOT: INFO

#    org.springframework.r2dbc: DEBUG

# ---------- Настройка логирования request-ов и response-ов (и ошибок) REST сервиса ------------------------------------
    # Вывод request-ов (ERROR,WARN - ничего кроме ошибок, INFO - request без body; DEBUG - request + body)
    ua.mai.zyme.r2dbcmysql.log.RequestLogWebFilter: DEBUG
    # Вывод response-ов (ERROR,WARN - ничего, INFO - response без body; DEBUG - response + body)
    ua.mai.zyme.r2dbcmysql.log.ResponseLogWebFilter: DEBUG
    # Вывод названий вызываемых методов контроллера (DEBUG):
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: DEBUG
    # -- Вывод различной доп. информации ------------------------------------------------------------------
    # Вывод request и response (DEBUG - краткая информация о request и response):
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: INFO
    # Вывод доп. информации о привязке запроса к вызываемому методу контроллера (DEBUG):
    org.springframework.web.reactive.result.method.annotation.RequestBodyMethodArgumentResolver: INFO
    # Вывод доп. информации о response (DEBUG):
    org.springframework.web.reactive.result.method.annotation.ResponseBodyResultHandler: INFO
    # Вывод доп. информации об Encoding тела ответа в JSON (DEBUG):
    org.springframework.http.codec: INFO
    # Вывод доп. информации об Encoding тела ответа (DEBUG):
    org.springframework.web.HttpLogging: INFO
# ----------------------------------------------------------------------------------------------------------------------

    # Вывод SQL в r2dbc:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG

    # Для отладки транзакций:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.transaction: TRACE

    # Для отладки сервисов
    ua.mai.zyme.db.transaction: DEBUG
    ua.mai.zyme.db.jooq: DEBUG
    ua.mai.zyme.db.jdbc: DEBUG

    # Для отладки JdbcTemplate и NamedParameterJdbcTemplate (и логирование параметров операторов):
    # logging statements:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    # log parameters of prepared statements:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.support.JdbcAccessor: TRACE

server:
  port: 8080
  address: localhost
spring:
  main.banner-mode: off
  application:
    name: r2dbc-mysql REST service

  r2dbc:
    url: r2dbc:mysql://localhost:3306/zyme
    username: root
    password: root

    pool.enabled: true
    pool.initial-size: 5
    pool.max-size: 10

  jackson.deserialization.fail-on-unknown-properties: true
