version: '3.7'

# Need to create network for work docker stack:
# $ docker network create --attachable --driver overlay zyme-net

services:
  r2dbc-mysql-mock-server:
    image: r2dbc-mysql-mock-server
    build:
      context: ../
      dockerfile: /src/main/docker/Dockerfile
#      args:
#        appVersion: ${APP_VERSION:-latest}
#        gitcommithash: ${GIT_HASH:-latest}
    ports:
      - 8090:3000
    networks:
      - zyme-net
    environment:
      - SERVER_PORT=3000
      - MOCKSERVER_LOG_LEVEL=DEBUG
      - MOCKSERVER_INITIALIZATION_CLASS=ua.mai.zyme.mockserver.r2dbcmysql.ExpectationInitializerImpl
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/libs/initializerJson.json
networks:
  zyme-net:
    external: true
