logging:
  level:
    ROOT: INFO

#    org.springframework.r2dbc: DEBUG

    ua.mai.zyme.r2dbcmysql.log.RequestLogWebFilter: DEBUG
    ua.mai.zyme.r2dbcmysql.log.ResponseLogWebFilter: DEBUG

    # Вывод SQL:
    org.springframework.r2dbc.core.DefaultDatabaseClient: DEBUG
    # Вывод request и response:
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    # Вывод названия вызываемого метода контроллера:
    org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping: DEBUG
    # Вывод доп. информации о привязке запроса к вызываемому методу контроллера (DEBUG):
    org.springframework.web.reactive.result.method.annotation.RequestBodyMethodArgumentResolver: INFO
    # Вывод доп. информации о response (DEBUG):
    org.springframework.web.reactive.result.method.annotation.ResponseBodyResultHandler: INFO
    # Вывод доп. информации об Encoding тела ответа в JSON (DEBUG):
    org.springframework.http.codec: INFO
    # Вывод доп. информации об Encoding тела ответа (DEBUG):
    org.springframework.web.HttpLogging: INFO

    # Для отладки транзакций:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.transaction: TRACE

    # Для отладки сервисов
    ua.mai.zyme.db.transaction: DEBUG
    ua.mai.zyme.db.jooq: DEBUG
    ua.mai.zyme.db.jdbc: DEBUG

    # Для отладки JdbcTemplate и NamedParameterJdbcTemplate (и логирование параметров операторов):
    # logging statements:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    # log parameters of prepared statements:
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.support.JdbcAccessor: TRACE

spring:
  application:
    name: r2dbc-mysql

  r2dbc:
#    url=r2dbc:postgresql://postgres:password@localhost:5432/postgres
    url: r2dbc:mysql://localhost:3306/trt
    username: root
    password: root

    pool.enabled: true
    pool.initial-size: 5
    pool.max-size: 10

