#schema: ./*.graphql

#projects:
#  default:
#    schema: 'schema.graphql'
#    documents: '**/*.graphql'
#  bar:
#    schema: './packages/bar/schema.graphql'

#schema: schema.graphql
#documents: '**/*.graphql'
